hydra:
  run:
    dir: ./experiments/${now:%Y-%m-%d}/Spring/${now:%H-%M-%S}_seq9

scene:
  background:
    # MLP
    n_layers: 6
    hidden_dim: 64

    # Fourier Features
    n_features: 64
    gauss_scale: 5.0

  local_representation:
    # MLP
    n_layers: 6
    hidden_dim: 64

    # Fourier Features
    n_features: 64
    gauss_scale: 2.2

ode:
  use_adjoint: False
  use_damping: False
  c_init: 0.6
  l_pendulum_init: 1.9
  init_with_gt: False

online_training:
  enable: True
  stepsize: 10
  start_length: 5

loss:
  weight_regularization_mask: 0.0005
  regularize_after_epochs: 400

optimizer:
  epochs: 1201
  background:
    lr_repr: 0.001
    lr_scheduler_gamma_repr: 0.9954
    lr_scheduler_step_size_repr: 50
  object:
    lr_repr: 0.001
    lr_scheduler_gamma_repr: 0.9954
    lr_scheduler_step_size_repr: 50
  physics:
    lr_physics: 0.005
    lr_scheduler_gamma_physics: 1
    lr_scheduler_step_size_physics: 100

data:
  data_root: /home/jan/Documents/TUDelftMSc/CVDL/project/project/data/datasets
  path_data: 'pendulum/pendulum_sl12.npz'
  batch_idx: 9
  training_length: 12
  prediction_length: 30

dataloader:
  batch_size: 65536
  shuffle: True
  num_workers: 8

logging:
  enable: True
  test_interval: 20
  logging_interval: 10
  checkpoint_interval: 100

seed: 42
