hydra:
  run:
    dir: ./experiments/${now:%Y-%m-%d}/sliding_block_cvdl/${now:%H-%M-%S}_seq9

scene:
  background:
    # MLP
    n_layers: 8
    hidden_dim: 512

    # Fourier Features
    n_features: 256
    gauss_scale: 30.0

  local_representation:
    # MLP
    n_layers: 8

    # Forier Features
    n_features: 128
    gauss_scale: 15.0

ode:
  use_adjoint: False
  mu_init: 0.0

online_training:
  enable: True
  stepsize: 10
  start_length: 5

loss:
  weight_regularization_mask: 0.0005
  regularize_after_epochs: 100

optimizer:
  epochs: 2001
  background:
    lr_repr: 0.001
    lr_scheduler_gamma_repr: 0.9954
    lr_scheduler_step_size_repr: 50
  object:
    lr_repr: 0.001
    lr_scheduler_gamma_repr: 0.9954
    lr_scheduler_step_size_repr: 50
  physics:
    lr_physics: 0.005
    lr_scheduler_gamma_physics: 1
    lr_scheduler_step_size_physics: 100

data:
  data_root: /home/jan/Documents/TUDelftMSc/CVDL/project/project/data/datasets
  path_data: 'sliding_block_real/sliding_block_real_sl42.npz'
  batch_idx: 0
  training_length: 12
  prediction_length: 42
  dt: 0.017

dataloader:
  batch_size: 65536
  shuffle: True
  num_workers: 8

logging:
  enable: True
  test_interval: 20
  logging_interval: 10
  checkpoint_interval: 100

seed: 42
